
services:
  bot:
    container_name: main-bot
    build: .
    env_file: .env
    depends_on:
      db:
        condition: service_healthy  # Зависимость от состояния здоровья базы данных
    volumes:
      - .:/app
    networks:
      - main-network
    command: sh -c "python MySqlConnection.py && python bot.py"

  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: TICKET_DATABASE
      MYSQL_PASSWORD: 655feda
      MYSQL_USER: fedyarik
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - main-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:

networks:
  main-network:
    driver: bridge
